# Generated by Django 2.2 on 2020-01-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospitaluser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaluser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Rejected'), (3, 'Deleted')], default=0, verbose_name='status'),
        ),
    ]
