# Generated by Django 2.2 on 2020-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20200118_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
    ]
