# Generated by Django 2.2 on 2020-01-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20200118_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='status'),
        ),
    ]
